[CmdletBinding()]
param(
    [string]$KeystorePath,
    [string]$Repo,
    [SecureString]$StorePassword,
    [string]$KeyAlias,
    [SecureString]$KeyPassword,
    [int]$ValidityDays = 10000,
    [string]$DistinguishedName = "CN=ChessPoints Release, OU=Maintainers, O=ChessPoints, L=Unknown, S=Unknown, C=US",
    [switch]$Force,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
$defaultKeystorePath = Join-Path $repoRoot "release.keystore"
$defaultKeyAlias = "chesspoints"
$validityWasProvided = $PSBoundParameters.ContainsKey("ValidityDays")
$autoGeneratedStorePassword = $false
$autoGeneratedKeyPassword = $false

function Write-Step([string]$Message) {
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Write-Note([string]$Message) {
    Write-Host "    $Message" -ForegroundColor DarkGray
}

function Fail([string]$Message) {
    [Console]::Error.WriteLine("ERROR: $Message")
    exit 1
}

function Get-JavaMajorVersion([string]$JavaExecutable) {
    # java -version writes its banner to stderr; capture it without treating it as a script error.
    $savedErrorActionPreference = $ErrorActionPreference
    try {
        $ErrorActionPreference = "Continue"
        $versionOutput = & $JavaExecutable -version 2>&1
    }
    finally {
        $ErrorActionPreference = $savedErrorActionPreference
    }

    if ($LASTEXITCODE -ne 0) {
        return $null
    }

    $firstLine = ($versionOutput | Select-Object -First 1)
    if ($firstLine -match '"(?<version>\d+)(\.\d+)?') {
        return [int]$Matches["version"]
    }

    return $null
}

function Ensure-JavaHome([int]$MinimumMajorVersion = 17) {
    if ($env:JAVA_HOME) {
        $configuredJava = Join-Path $env:JAVA_HOME "bin\java.exe"
        if (Test-Path $configuredJava) {
            $configuredMajor = Get-JavaMajorVersion -JavaExecutable $configuredJava
            if ($configuredMajor -ge $MinimumMajorVersion) {
                Write-Step "Using JAVA_HOME at $env:JAVA_HOME"
                return
            }
        }
    }

    $candidates = @(
        "C:\Program Files\Eclipse Adoptium\jdk-17.0.20.101-hotspot",
        "C:\Program Files\Eclipse Adoptium\jdk-17",
        "C:\Program Files\Android\Android Studio\jbr",
        "C:\Program Files\Microsoft\jdk-17.0.11.9-hotspot",
        "C:\Program Files\Java\jdk-17",
        "C:\Program Files\Java\jdk-21",
        "C:\Program Files\Java\jdk-11"
    )

    foreach ($candidate in $candidates) {
        $javaExecutable = Join-Path $candidate "bin\java.exe"
        if (-not (Test-Path $javaExecutable)) {
            continue
        }

        $majorVersion = Get-JavaMajorVersion -JavaExecutable $javaExecutable
        if ($majorVersion -ge $MinimumMajorVersion) {
            $env:JAVA_HOME = $candidate
            $env:Path = "$candidate\bin;$env:Path"
            Write-Step "Using detected JDK at $candidate"
            return
        }
    }

    Fail "JAVA_HOME is not set to a JDK $MinimumMajorVersion+ installation and no fallback JDK was found. Install JDK 17+, set JAVA_HOME, and retry."
}

function Get-KeytoolPath {
    Ensure-JavaHome
    $keytoolPath = Join-Path $env:JAVA_HOME "bin\keytool.exe"
    if (-not (Test-Path $keytoolPath)) {
        Fail "keytool.exe was not found under JAVA_HOME ($env:JAVA_HOME). Install a full JDK 17+ and retry."
    }

    return $keytoolPath
}

function Ensure-GhAuthenticated {
    $ghCommand = Get-Command gh -ErrorAction SilentlyContinue
    if (-not $ghCommand) {
        Fail "GitHub CLI (gh) is not installed or not on PATH. Install it, run 'gh auth login', and retry."
    }

    Write-Step "Checking GitHub CLI authentication"
    & $ghCommand.Source auth status 1>$null 2>$null
    if ($LASTEXITCODE -ne 0) {
        Fail "GitHub CLI is not authenticated. Run 'gh auth login' and retry."
    }

    return $ghCommand.Source
}

function Resolve-Repo([string]$RepoValue, [string]$GhPath) {
    if ($RepoValue) {
        return $RepoValue
    }

    Write-Step "Detecting target GitHub repository"
    Push-Location $repoRoot
    try {
        $detectedRepoRaw = & $GhPath repo view --json nameWithOwner -q .nameWithOwner 2>$null
    }
    finally {
        Pop-Location
    }

    $detectedRepo = if ($detectedRepoRaw) { $detectedRepoRaw.Trim() } else { $null }

    if (-not $detectedRepo) {
        Fail "Could not detect the target repo from this checkout. Pass -Repo owner/repo and retry."
    }

    return $detectedRepo
}

function Resolve-KeystorePath([string]$ProvidedPath) {
    if ($ProvidedPath) {
        if ([System.IO.Path]::IsPathRooted($ProvidedPath)) {
            return [System.IO.Path]::GetFullPath($ProvidedPath)
        }

        return [System.IO.Path]::GetFullPath((Join-Path $repoRoot $ProvidedPath))
    }

    if (Test-Path $defaultKeystorePath) {
        Write-Step "Using default keystore path at $defaultKeystorePath"
        return $defaultKeystorePath
    }

    if ($Force) {
        Write-Step "Defaulting keystore path to $defaultKeystorePath"
        return $defaultKeystorePath
    }

    $entered = Read-Host "Keystore path [$defaultKeystorePath]"
    if ([string]::IsNullOrWhiteSpace($entered)) {
        return $defaultKeystorePath
    }

    if ([System.IO.Path]::IsPathRooted($entered)) {
        return [System.IO.Path]::GetFullPath($entered)
    }

    return [System.IO.Path]::GetFullPath((Join-Path $repoRoot $entered))
}

function Read-RequiredText(
    [string]$CurrentValue,
    [string]$Prompt,
    [string]$DefaultValue = ""
) {
    if (-not [string]::IsNullOrWhiteSpace($CurrentValue)) {
        return $CurrentValue
    }

    if ($Force) {
        if (-not [string]::IsNullOrWhiteSpace($DefaultValue)) {
            return $DefaultValue
        }

        Fail "$Prompt is required when -Force is used."
    }

    $fullPrompt = if ([string]::IsNullOrWhiteSpace($DefaultValue)) {
        $Prompt
    } else {
        "$Prompt [$DefaultValue]"
    }

    $entered = Read-Host $fullPrompt
    if ([string]::IsNullOrWhiteSpace($entered)) {
        if (-not [string]::IsNullOrWhiteSpace($DefaultValue)) {
            return $DefaultValue
        }

        Fail "$Prompt is required."
    }

    return $entered.Trim()
}

function New-RandomSecureString {
    $bytes = New-Object byte[] 24
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $plain = [Convert]::ToHexString($bytes)
    return ConvertTo-SecureString -String $plain -AsPlainText -Force
}

function Read-RequiredSecret(
    [SecureString]$CurrentValue,
    [string]$Prompt,
    [switch]$AllowReuseStorePassword,
    [SecureString]$StorePasswordValue,
    [switch]$AllowAutoGenerateWhenForced
) {
    if ($CurrentValue) {
        return $CurrentValue
    }

    if ($Force) {
        if ($AllowReuseStorePassword -and $StorePasswordValue) {
            return $StorePasswordValue
        }

        if ($AllowAutoGenerateWhenForced) {
            return New-RandomSecureString
        }

        Fail "$Prompt is required when -Force is used."
    }

    if ($AllowReuseStorePassword -and $StorePasswordValue) {
        $reuse = Read-Host "$Prompt (press Enter to reuse the store password, or type anything to enter a separate value)"
        if ([string]::IsNullOrWhiteSpace($reuse)) {
            return $StorePasswordValue
        }
    }

    $entered = Read-Host -AsSecureString $Prompt
    if (-not $entered) {
        Fail "$Prompt is required."
    }

    return $entered
}

function Get-PlainText([SecureString]$SecureValue) {
    if (-not $SecureValue) {
        return $null
    }

    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureValue)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    }
    finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }
}

function Should-GenerateKeystore([string]$Path) {
    if ($DryRun -or $Force) {
        return $true
    }

    $answer = Read-Host "Keystore not found at '$Path'. Generate one now? [Y/n]"
    return [string]::IsNullOrWhiteSpace($answer) -or $answer.Trim().ToLowerInvariant() -eq "y"
}

function Ensure-KeystoreDirectory([string]$Path) {
    $parent = Split-Path -Parent $Path
    if (-not [string]::IsNullOrWhiteSpace($parent) -and -not (Test-Path $parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
}

function Resolve-ValidityDays([int]$CurrentValue) {
    if ($validityWasProvided -or $Force) {
        if ($CurrentValue -lt 1) {
            Fail "ValidityDays must be 1 or greater."
        }

        return $CurrentValue
    }

    $entered = Read-Host "Certificate validity in days [$CurrentValue]"
    if ([string]::IsNullOrWhiteSpace($entered)) {
        return $CurrentValue
    }

    $parsed = 0
    if (-not [int]::TryParse($entered, [ref]$parsed) -or $parsed -lt 1) {
        Fail "ValidityDays must be a positive integer."
    }

    return $parsed
}

function Invoke-KeytoolGenerate(
    [string]$KeytoolPath,
    [string]$ResolvedKeystorePath,
    [SecureString]$ResolvedStorePassword,
    [string]$ResolvedKeyAlias,
    [SecureString]$ResolvedKeyPassword,
    [int]$ResolvedValidityDays,
    [string]$ResolvedDistinguishedName
) {
    $storePlain = Get-PlainText $ResolvedStorePassword
    $keyPlain = Get-PlainText $ResolvedKeyPassword

    try {
        if ($DryRun) {
            Write-Step "Dry run: would generate a new keystore"
            Write-Note "Path: $ResolvedKeystorePath"
            Write-Note "Alias: $ResolvedKeyAlias"
            Write-Note "Validity days: $ResolvedValidityDays"
            Write-Note "Distinguished name: $ResolvedDistinguishedName"
            Write-Note "Passwords are hidden and no file will be written."
            return
        }

        Ensure-KeystoreDirectory -Path $ResolvedKeystorePath

        & $KeytoolPath `
            -genkeypair `
            -v `
            -keystore $ResolvedKeystorePath `
            -storepass $storePlain `
            -alias $ResolvedKeyAlias `
            -keypass $keyPlain `
            -keyalg RSA `
            -keysize 2048 `
            -validity $ResolvedValidityDays `
            -dname $ResolvedDistinguishedName

        if ($LASTEXITCODE -ne 0) {
            Fail "keytool failed while generating the keystore."
        }
    }
    finally {
        if ($storePlain) {
            $storePlain = $null
        }
        if ($keyPlain) {
            $keyPlain = $null
        }
    }
}

function ConvertTo-WindowsProcessArgument([string]$Value) {
    if ($null -eq $Value -or $Value.Length -eq 0) {
        return '""'
    }

    $builder = New-Object System.Text.StringBuilder
    [void]$builder.Append('"')
    $backslashCount = 0

    foreach ($character in $Value.ToCharArray()) {
        if ($character -eq '\') {
            $backslashCount++
            continue
        }

        if ($character -eq '"') {
            [void]$builder.Append(('\' * (($backslashCount * 2) + 1)))
            [void]$builder.Append('"')
        } else {
            if ($backslashCount -gt 0) {
                [void]$builder.Append(('\' * $backslashCount))
            }
            [void]$builder.Append($character)
        }

        $backslashCount = 0
    }

    if ($backslashCount -gt 0) {
        [void]$builder.Append(('\' * ($backslashCount * 2)))
    }
    [void]$builder.Append('"')
    return $builder.ToString()
}

function Invoke-GhSecretSet([string]$GhPath, [string]$RepoName, [string]$SecretName, [string]$SecretValue) {
    if ($DryRun) {
        Write-Step "Dry run: would set $SecretName on $RepoName"
        return
    }

    $startInfo = New-Object System.Diagnostics.ProcessStartInfo
    $startInfo.FileName = $GhPath
    $argumentValues = @("secret", "set", $SecretName, "--repo", $RepoName)
    if ($null -ne $startInfo.PSObject.Properties["ArgumentList"]) {
        foreach ($argumentValue in $argumentValues) {
            [void]$startInfo.ArgumentList.Add($argumentValue)
        }
    } else {
        # Windows PowerShell/.NET Framework does not expose ArgumentList.
        $startInfo.Arguments = ($argumentValues | ForEach-Object {
            ConvertTo-WindowsProcessArgument $_
        }) -join " "
    }
    $startInfo.RedirectStandardInput = $true
    $startInfo.RedirectStandardOutput = $true
    $startInfo.RedirectStandardError = $true
    $startInfo.UseShellExecute = $false
    $startInfo.CreateNoWindow = $true

    $process = New-Object System.Diagnostics.Process
    $process.StartInfo = $startInfo
    $null = $process.Start()

    try {
        $process.StandardInput.Write($SecretValue)
        $process.StandardInput.Close()
        $stdout = $process.StandardOutput.ReadToEnd()
        $stderr = $process.StandardError.ReadToEnd()
        $process.WaitForExit()
        $exitCode = $process.ExitCode
    }
    finally {
        $process.Dispose()
    }

    if ($stdout) {
        Write-Note ($stdout.Trim())
    }

    if ($exitCode -ne 0) {
        if ($stderr) {
            [Console]::Error.WriteLine($stderr.Trim())
        }

        Fail "Failed to set GitHub secret $SecretName."
    }
}

$ghPath = Ensure-GhAuthenticated
$resolvedRepo = Resolve-Repo -RepoValue $Repo -GhPath $ghPath
Write-Step "Target repo: $resolvedRepo"

$resolvedKeystorePath = Resolve-KeystorePath -ProvidedPath $KeystorePath
$resolvedKeyAlias = $KeyAlias
$resolvedStorePassword = $StorePassword
$resolvedKeyPassword = $KeyPassword

if (Test-Path $resolvedKeystorePath) {
    Write-Step "Using existing keystore at $resolvedKeystorePath"
    $resolvedKeyAlias = Read-RequiredText -CurrentValue $resolvedKeyAlias -Prompt "Key alias"
    $resolvedStorePassword = Read-RequiredSecret -CurrentValue $resolvedStorePassword -Prompt "Keystore password"
    $resolvedKeyPassword = Read-RequiredSecret -CurrentValue $resolvedKeyPassword -Prompt "Key password" -AllowReuseStorePassword -StorePasswordValue $resolvedStorePassword
} else {
    if (-not (Should-GenerateKeystore -Path $resolvedKeystorePath)) {
        Fail "No keystore is available. Provide -KeystorePath for an existing one, or allow the script to generate a new keystore."
    }

    $keytoolPath = Get-KeytoolPath
    Write-Step "Using keytool at $keytoolPath"

    $resolvedKeyAlias = Read-RequiredText -CurrentValue $resolvedKeyAlias -Prompt "Key alias" -DefaultValue $defaultKeyAlias
    $resolvedStorePassword = Read-RequiredSecret -CurrentValue $resolvedStorePassword -Prompt "Keystore password" -AllowAutoGenerateWhenForced
    $resolvedKeyPassword = Read-RequiredSecret -CurrentValue $resolvedKeyPassword -Prompt "Key password" -AllowReuseStorePassword -StorePasswordValue $resolvedStorePassword -AllowAutoGenerateWhenForced
    $ValidityDays = Resolve-ValidityDays -CurrentValue $ValidityDays

    if ($Force -and -not $StorePassword) {
        $autoGeneratedStorePassword = $true
    }
    if ($Force -and -not $KeyPassword) {
        $autoGeneratedKeyPassword = -not $resolvedKeyPassword.Equals($resolvedStorePassword)
    }

    Invoke-KeytoolGenerate `
        -KeytoolPath $keytoolPath `
        -ResolvedKeystorePath $resolvedKeystorePath `
        -ResolvedStorePassword $resolvedStorePassword `
        -ResolvedKeyAlias $resolvedKeyAlias `
        -ResolvedKeyPassword $resolvedKeyPassword `
        -ResolvedValidityDays $ValidityDays `
        -ResolvedDistinguishedName $DistinguishedName
}

if (-not $DryRun -and -not (Test-Path $resolvedKeystorePath)) {
    Fail "Keystore not found at $resolvedKeystorePath after generation."
}

$storePasswordPlain = Get-PlainText $resolvedStorePassword
$keyPasswordPlain = Get-PlainText $resolvedKeyPassword

try {
    if ($DryRun) {
        Write-Step "Dry run: would base64-encode $resolvedKeystorePath"
    } else {
        Write-Step "Base64-encoding keystore"
        $keystoreBase64 = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($resolvedKeystorePath))
    }

    Write-Step "Setting GitHub Actions secrets"
    Invoke-GhSecretSet -GhPath $ghPath -RepoName $resolvedRepo -SecretName "RELEASE_KEYSTORE_BASE64" -SecretValue $(if ($DryRun) { "<base64 keystore bytes>" } else { $keystoreBase64 })
    Invoke-GhSecretSet -GhPath $ghPath -RepoName $resolvedRepo -SecretName "RELEASE_KEYSTORE_PASSWORD" -SecretValue $(if ($DryRun) { "<hidden>" } else { $storePasswordPlain })
    Invoke-GhSecretSet -GhPath $ghPath -RepoName $resolvedRepo -SecretName "RELEASE_KEY_ALIAS" -SecretValue $resolvedKeyAlias
    Invoke-GhSecretSet -GhPath $ghPath -RepoName $resolvedRepo -SecretName "RELEASE_KEY_PASSWORD" -SecretValue $(if ($DryRun) { "<hidden>" } else { $keyPasswordPlain })

    Write-Step "Success"
    Write-Host "Configured secrets for ${resolvedRepo}:" -ForegroundColor Green
    Write-Host " - RELEASE_KEYSTORE_BASE64" -ForegroundColor Green
    Write-Host " - RELEASE_KEYSTORE_PASSWORD" -ForegroundColor Green
    Write-Host " - RELEASE_KEY_ALIAS" -ForegroundColor Green
    Write-Host " - RELEASE_KEY_PASSWORD" -ForegroundColor Green
    if ($autoGeneratedStorePassword -or $autoGeneratedKeyPassword) {
        Write-Host "One or more passwords were auto-generated because -Force was used without explicit password parameters. Store your keystore details safely outside the repo if you need to reproduce local release signing later." -ForegroundColor Yellow
    }
    if ($DryRun) {
        Write-Host "No secrets were changed and no keystore file was written because -DryRun was used." -ForegroundColor Yellow
    }
}
finally {
    if ($storePasswordPlain) {
        $storePasswordPlain = $null
    }
    if ($keyPasswordPlain) {
        $keyPasswordPlain = $null
    }
    if ($keystoreBase64) {
        $keystoreBase64 = $null
    }
}
